### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './output/LSTM_1000_0'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/word_prediction#2]
```
> train.txt : Building vocabulary. Processed 6470000, vocabulary size = 10102
> train.txt : Converting data. Processed 6470000
> valid.txt : Building vocabulary. Processed 10, vocabulary size = 10102
> valid.txt : Converting data. Processed 10
> test.txt : Building vocabulary. Processed 361, vocabulary size = 10102
> test.txt : Converting data. Processed 361
> chr: The seeds are [3099, 1933, 896, 3335, 3041, 1091], the seed indices are [0, 1, 2, 3, 4, 5]
Initialised Model: <bound method Module.parameters of RNNModel(
  (drop): Dropout(p=0, inplace=False)
  (encoder): Embedding(10102, 400)
  (rnn): LSTM(400, 500)
  (predecoder): Linear(in_features=500, out_features=400, bias=True)
  (tanh): Tanh()
  (decoder): Linear(in_features=400, out_features=10102, bias=True)
)>
Traceback (most recent call last):
  File "main.py", line 256, in <module>
    train(seed_index, t_plus_one=True)
  File "main.py", line 182, in train
    with open(args.save+args.model+'_'+str(batch+1)+'_'+str(seed_index), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './output/LSTM_1000_0'
```

**Comment by ys7yoo** [comment]
make `output` folder
